// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chunk.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertChunk = `-- name: InsertChunk :one
INSERT INTO chunks (
    id,
    document_version_id,
    kb_id,
    sequence_number,
    content,
    content_hash,
    metadata,
    chunking_strategy,
    embedding_id,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, document_version_id, kb_id, sequence_number, content, content_hash, metadata, chunking_strategy, embedding_id, created_at
`

type InsertChunkParams struct {
	ID                uuid.UUID       `json:"id"`
	DocumentVersionID uuid.UUID       `json:"document_version_id"`
	KbID              uuid.UUID       `json:"kb_id"`
	SequenceNumber    int32           `json:"sequence_number"`
	Content           string          `json:"content"`
	ContentHash       string          `json:"content_hash"`
	Metadata          json.RawMessage `json:"metadata"`
	ChunkingStrategy  string          `json:"chunking_strategy"`
	EmbeddingID       uuid.NullUUID   `json:"embedding_id"`
	CreatedAt         time.Time       `json:"created_at"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) (Chunk, error) {
	row := q.db.QueryRowContext(ctx, insertChunk,
		arg.ID,
		arg.DocumentVersionID,
		arg.KbID,
		arg.SequenceNumber,
		arg.Content,
		arg.ContentHash,
		arg.Metadata,
		arg.ChunkingStrategy,
		arg.EmbeddingID,
		arg.CreatedAt,
	)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.DocumentVersionID,
		&i.KbID,
		&i.SequenceNumber,
		&i.Content,
		&i.ContentHash,
		&i.Metadata,
		&i.ChunkingStrategy,
		&i.EmbeddingID,
		&i.CreatedAt,
	)
	return i, err
}
