// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getDocumentByKBPath = `-- name: GetDocumentByKBPath :one
SELECT id, kb_id, path, title, document_type, source_metadata, active_version_id, created_at, updated_at FROM documents
WHERE kb_id = $1 AND path = $2
`

type GetDocumentByKBPathParams struct {
	KbID uuid.UUID `json:"kb_id"`
	Path string    `json:"path"`
}

func (q *Queries) GetDocumentByKBPath(ctx context.Context, arg GetDocumentByKBPathParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByKBPath, arg.KbID, arg.Path)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.KbID,
		&i.Path,
		&i.Title,
		&i.DocumentType,
		&i.SourceMetadata,
		&i.ActiveVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO documents (
    id,
    kb_id,
    path,
    title,
    document_type,
    source_metadata,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, kb_id, path, title, document_type, source_metadata, active_version_id, created_at, updated_at
`

type InsertDocumentParams struct {
	ID             uuid.UUID       `json:"id"`
	KbID           uuid.UUID       `json:"kb_id"`
	Path           string          `json:"path"`
	Title          sql.NullString  `json:"title"`
	DocumentType   string          `json:"document_type"`
	SourceMetadata json.RawMessage `json:"source_metadata"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, insertDocument,
		arg.ID,
		arg.KbID,
		arg.Path,
		arg.Title,
		arg.DocumentType,
		arg.SourceMetadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.KbID,
		&i.Path,
		&i.Title,
		&i.DocumentType,
		&i.SourceMetadata,
		&i.ActiveVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDocumentVersion = `-- name: InsertDocumentVersion :one
INSERT INTO document_versions (
    id,
    document_id,
    kb_id,
    version_number,
    raw_content_uri,
    processing_status,
    error_message,
    is_active,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    (SELECT COALESCE(MAX(version_number), 0) + 1 FROM document_versions WHERE document_id = $2),
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, document_id, kb_id, version_number, raw_content_uri, extracted_content, extracted_content_hash, processing_status, error_message, is_active, created_at
`

type InsertDocumentVersionParams struct {
	ID               uuid.UUID      `json:"id"`
	DocumentID       uuid.UUID      `json:"document_id"`
	KbID             uuid.UUID      `json:"kb_id"`
	RawContentUri    string         `json:"raw_content_uri"`
	ProcessingStatus string         `json:"processing_status"`
	ErrorMessage     sql.NullString `json:"error_message"`
	IsActive         bool           `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
}

func (q *Queries) InsertDocumentVersion(ctx context.Context, arg InsertDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRowContext(ctx, insertDocumentVersion,
		arg.ID,
		arg.DocumentID,
		arg.KbID,
		arg.RawContentUri,
		arg.ProcessingStatus,
		arg.ErrorMessage,
		arg.IsActive,
		arg.CreatedAt,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.KbID,
		&i.VersionNumber,
		&i.RawContentUri,
		&i.ExtractedContent,
		&i.ExtractedContentHash,
		&i.ProcessingStatus,
		&i.ErrorMessage,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET title = $2,
    document_type = $3,
    source_metadata = $4,
    updated_at = $5
WHERE id = $1
RETURNING id, kb_id, path, title, document_type, source_metadata, active_version_id, created_at, updated_at
`

type UpdateDocumentParams struct {
	ID             uuid.UUID       `json:"id"`
	Title          sql.NullString  `json:"title"`
	DocumentType   string          `json:"document_type"`
	SourceMetadata json.RawMessage `json:"source_metadata"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.DocumentType,
		arg.SourceMetadata,
		arg.UpdatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.KbID,
		&i.Path,
		&i.Title,
		&i.DocumentType,
		&i.SourceMetadata,
		&i.ActiveVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentVersionStatus = `-- name: UpdateDocumentVersionStatus :exec
UPDATE document_versions
SET processing_status = $2,
    error_message = $3
WHERE id = $1
`

type UpdateDocumentVersionStatusParams struct {
	ID               uuid.UUID      `json:"id"`
	ProcessingStatus string         `json:"processing_status"`
	ErrorMessage     sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateDocumentVersionStatus(ctx context.Context, arg UpdateDocumentVersionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentVersionStatus, arg.ID, arg.ProcessingStatus, arg.ErrorMessage)
	return err
}

const activateDocumentVersion = `-- name: ActivateDocumentVersion :exec
BEGIN;
UPDATE document_versions SET is_active = false
WHERE document_id = (SELECT document_id FROM document_versions WHERE id = $1);

UPDATE document_versions SET is_active = true, processing_status = 'ACTIVATED'
WHERE id = $1;

UPDATE documents SET active_version_id = $1, updated_at = now()
WHERE id = (SELECT document_id FROM document_versions WHERE id = $1);
COMMIT;
`

func (q *Queries) ActivateDocumentVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, activateDocumentVersion, id)
	return err
}
