// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embedding.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

const hasEmbedding = `-- name: HasEmbedding :one
SELECT 1
FROM embeddings
WHERE kb_id = $1
  AND content_hash = $2
  AND embedding_model_id = $3
LIMIT 1
`

type HasEmbeddingParams struct {
	KbID             uuid.UUID `json:"kb_id"`
	ContentHash      string    `json:"content_hash"`
	EmbeddingModelID string    `json:"embedding_model_id"`
}

func (q *Queries) HasEmbedding(ctx context.Context, arg HasEmbeddingParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, hasEmbedding,
		arg.KbID,
		arg.ContentHash,
		arg.EmbeddingModelID,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertEmbedding = `-- name: InsertEmbedding :exec
INSERT INTO embeddings (
    id,
    kb_id,
    content_hash,
    embedding_model_id,
    embedding_vector,
    created_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEmbeddingParams struct {
	ID                    uuid.UUID       `json:"id"`
	KbID                  uuid.UUID       `json:"kb_id"`
	ContentHash           string          `json:"content_hash"`
	EmbeddingModelID      string          `json:"embedding_model_id"`
	EmbeddingVector       pgvector.Vector `json:"embedding_vector"`
	CreatedAt             time.Time       `json:"created_at"`
}

func (q *Queries) InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, insertEmbedding,
		arg.ID,
		arg.KbID,
		arg.ContentHash,
		arg.EmbeddingModelID,
		arg.EmbeddingVector,
		arg.CreatedAt,
	)
	return err
}
