// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kb.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteKnowledgeBase = `-- name: DeleteKnowledgeBase :execrows
DELETE FROM knowledge_bases
WHERE id = $1
`

func (q *Queries) DeleteKnowledgeBase(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteKnowledgeBase, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getKnowledgeBase = `-- name: GetKnowledgeBase :one
SELECT id, name, metadata, created_at, updated_at FROM knowledge_bases
WHERE id = $1
`

func (q *Queries) GetKnowledgeBase(ctx context.Context, id uuid.UUID) (KnowledgeBasis, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeBase, id)
	var i KnowledgeBasis
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertKnowledgeBase = `-- name: InsertKnowledgeBase :one
INSERT INTO knowledge_bases (
    id,
    name,
    metadata,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, metadata, created_at, updated_at
`

type InsertKnowledgeBaseParams struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

func (q *Queries) InsertKnowledgeBase(ctx context.Context, arg InsertKnowledgeBaseParams) (KnowledgeBasis, error) {
	row := q.db.QueryRowContext(ctx, insertKnowledgeBase,
		arg.ID,
		arg.Name,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i KnowledgeBasis
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKnowledgeBases = `-- name: ListKnowledgeBases :many
SELECT id, name, metadata, created_at, updated_at FROM knowledge_bases
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListKnowledgeBases(ctx context.Context) ([]KnowledgeBasis, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeBases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeBasis
	for rows.Next() {
		var i KnowledgeBasis
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKnowledgeBase = `-- name: UpdateKnowledgeBase :one
UPDATE knowledge_bases
SET name = $2,
    metadata = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, name, metadata, created_at, updated_at
`

type UpdateKnowledgeBaseParams struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Metadata  json.RawMessage `json:"metadata"`
	UpdatedAt time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateKnowledgeBase(ctx context.Context, arg UpdateKnowledgeBaseParams) (KnowledgeBasis, error) {
	row := q.db.QueryRowContext(ctx, updateKnowledgeBase,
		arg.ID,
		arg.Name,
		arg.Metadata,
		arg.UpdatedAt,
	)
	var i KnowledgeBasis
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
