// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

type Chunk struct {
	ID                uuid.UUID       `json:"id"`
	DocumentVersionID uuid.UUID       `json:"document_version_id"`
	KbID              uuid.UUID       `json:"kb_id"`
	SequenceNumber    int32           `json:"sequence_number"`
	Content           string          `json:"content"`
	ContentHash       string          `json:"content_hash"`
	Metadata          json.RawMessage `json:"metadata"`
	ChunkingStrategy  string          `json:"chunking_strategy"`
	EmbeddingID       uuid.NullUUID   `json:"embedding_id"`
	CreatedAt         time.Time       `json:"created_at"`
}

type Document struct {
	ID              uuid.UUID       `json:"id"`
	KbID            uuid.UUID       `json:"kb_id"`
	Path            string          `json:"path"`
	Title           sql.NullString  `json:"title"`
	DocumentType    string          `json:"document_type"`
	SourceMetadata  json.RawMessage `json:"source_metadata"`
	ActiveVersionID uuid.NullUUID   `json:"active_version_id"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type DocumentVersion struct {
	ID                   uuid.UUID      `json:"id"`
	DocumentID           uuid.UUID      `json:"document_id"`
	KbID                 uuid.UUID      `json:"kb_id"`
	VersionNumber        int32          `json:"version_number"`
	RawContentUri        string         `json:"raw_content_uri"`
	ExtractedContent     sql.NullString `json:"extracted_content"`
	ExtractedContentHash sql.NullString `json:"extracted_content_hash"`
	ProcessingStatus     string         `json:"processing_status"`
	ErrorMessage         sql.NullString `json:"error_message"`
	IsActive             bool           `json:"is_active"`
	CreatedAt            time.Time      `json:"created_at"`
}

type Embedding struct {
	ID                    uuid.UUID       `json:"id"`
	KbID                  uuid.UUID       `json:"kb_id"`
	ContentHash           string          `json:"content_hash"`
	EmbeddingModelID      string          `json:"embedding_model_id"`
	EmbeddingVector       pgvector.Vector `json:"embedding_vector"`
	CreatedAt             time.Time       `json:"created_at"`
}

type EmbeddingModel struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	VectorDimension int32           `json:"vector_dimension"`
	Provider        string          `json:"provider"`
	Parameters      json.RawMessage `json:"parameters"`
	IsActive        bool            `json:"is_active"`
	CreatedAt       time.Time       `json:"created_at"`
}

type Evaluation struct {
	ID          uuid.UUID      `json:"id"`
	KbID        uuid.UUID      `json:"kb_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

type EvaluationQuery struct {
	ID               uuid.UUID       `json:"id"`
	EvaluationID     uuid.UUID       `json:"evaluation_id"`
	Query            string          `json:"query"`
	ExpectedChunkIds json.RawMessage `json:"expected_chunk_ids"`
	CreatedAt        time.Time       `json:"created_at"`
}

type EvaluationResult struct {
	ID                uuid.UUID       `json:"id"`
	EvaluationID      uuid.UUID       `json:"evaluation_id"`
	QueryID           uuid.UUID       `json:"query_id"`
	RetrievedChunkIds json.RawMessage `json:"retrieved_chunk_ids"`
	RecallAtK         float64         `json:"recall_at_k"`
	PrecisionAtK      float64         `json:"precision_at_k"`
	CreatedAt         time.Time       `json:"created_at"`
}

type IngestionJob struct {
	ID                uuid.UUID      `json:"id"`
	DocumentVersionID uuid.UUID      `json:"document_version_id"`
	KbID              uuid.UUID      `json:"kb_id"`
	JobStatus         string         `json:"job_status"`
	ErrorMessage      sql.NullString `json:"error_message"`
	StartedAt         sql.NullTime   `json:"started_at"`
	CompletedAt       sql.NullTime   `json:"completed_at"`
}

type KnowledgeBasis struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type ProcessingMetric struct {
	ID             uuid.UUID      `json:"id"`
	IngestionJobID uuid.UUID      `json:"ingestion_job_id"`
	Stage          string         `json:"stage"`
	DurationMs     int64          `json:"duration_ms"`
	ItemCount      int32          `json:"item_count"`
	Status         string         `json:"status"`
	ErrorMessage   sql.NullString `json:"error_message"`
	CreatedAt      time.Time      `json:"created_at"`
}

type RetrievalRequest struct {
	ID           uuid.UUID       `json:"id"`
	KbID         uuid.UUID       `json:"kb_id"`
	Query        string          `json:"query"`
	Filters      json.RawMessage `json:"filters"`
	TopK         int32           `json:"top_k"`
	HybridWeight float64         `json:"hybrid_weight"`
	ResultCount  int32           `json:"result_count"`
	LatencyMs    int64           `json:"latency_ms"`
	EmptyResult  bool            `json:"empty_result"`
	CreatedAt    time.Time       `json:"created_at"`
}

type RetrievalResult struct {
	ID                 uuid.UUID `json:"id"`
	RetrievalRequestID uuid.UUID `json:"retrieval_request_id"`
	ChunkID            uuid.UUID `json:"chunk_id"`
	Rank               int32     `json:"rank"`
	SemanticScore      float64   `json:"semantic_score"`
	LexicalScore       float64   `json:"lexical_score"`
	FinalScore         float64   `json:"final_score"`
	CreatedAt          time.Time `json:"created_at"`
}
