// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateDocumentVersion(ctx context.Context, id uuid.UUID) error
	DeleteKnowledgeBase(ctx context.Context, id uuid.UUID) (int64, error)
	GetChunksWithDocuments(ctx context.Context, chunkIds []uuid.UUID) ([]GetChunksWithDocumentsRow, error)
	GetDocumentByKBPath(ctx context.Context, arg GetDocumentByKBPathParams) (Document, error)
	GetKnowledgeBase(ctx context.Context, id uuid.UUID) (KnowledgeBasis, error)
	HasEmbedding(ctx context.Context, arg HasEmbeddingParams) (int32, error)
	InsertChunk(ctx context.Context, arg InsertChunkParams) (Chunk, error)
	InsertDocument(ctx context.Context, arg InsertDocumentParams) (Document, error)
	InsertDocumentVersion(ctx context.Context, arg InsertDocumentVersionParams) (DocumentVersion, error)
	InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) error
	InsertKnowledgeBase(ctx context.Context, arg InsertKnowledgeBaseParams) (KnowledgeBasis, error)
	InsertRetrievalRequest(ctx context.Context, arg InsertRetrievalRequestParams) (RetrievalRequest, error)
	InsertRetrievalResult(ctx context.Context, arg InsertRetrievalResultParams) error
	ListKnowledgeBases(ctx context.Context) ([]KnowledgeBasis, error)
	SearchLexical(ctx context.Context, arg SearchLexicalParams) ([]SearchLexicalRow, error)
	SearchSemantic(ctx context.Context, arg SearchSemanticParams) ([]SearchSemanticRow, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
	UpdateDocumentVersionStatus(ctx context.Context, arg UpdateDocumentVersionStatusParams) error
	UpdateKnowledgeBase(ctx context.Context, arg UpdateKnowledgeBaseParams) (KnowledgeBasis, error)
	UpdateRetrievalRequest(ctx context.Context, arg UpdateRetrievalRequestParams) error
}

var _ Querier = (*Queries)(nil)
